name: Release PyPi packages

on:
  workflow_dispatch:

jobs:
  publish-core:
    name: Build & publish pepedd (core)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "pepedd-core/uv.lock"

      - name: Build core
        run: |
          chmod +x build_core.sh
          ./build_core.sh
      - name: Publish core
        run: |
          echo $(pwd)
          uv publish $(pwd)/dist/* -t ${{ secrets.PYPI_TOKEN }}


  publish-nodes:
    name: Build & publish pepedd_nodes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "pepedd-nodes/uv.lock"

      - name: Build nodes
        run: |
          chmod +x build_nodes.sh
          ./build_nodes.sh

      - name: Publish nodes
        run: |
          echo $(pwd)
          uv publish $(pwd)/dist/* -t ${{ secrets.PYPI_TOKEN }}
